In [2]:
!pip install -Uq pymcel
!pip install -Uq rebound

In [3]:
import numpy as np
import pymcel as pc

Bienvenido a PyMCel v0.9.10 ¡al infinito y más allá!


In [6]:
tabla, jd, X_sol = pc.consulta_horizons(
    id = '@sun',
    location = '@SSB',
    epochs = '2026-02-26 00:00:00'
)
X_sol

array([-3.99267884e+08, -8.24090450e+08,  1.85429947e+07,  1.22108229e+01,
        1.23932702e+00, -2.42604119e-01])

In [9]:
tabla_jup, jd_jup, X_jup = pc.consulta_horizons(
    id = '@jupiter barycenter',
    location = '@SSB',
    epochs = '2026-02-26 00:00:00')

In [14]:
r_sol_0 = X_sol[:3]
v_sol_0 = X_sol[3:]

r_jup_0 = X_jup[:3]
v_jup_0 = X_jup[3:]

r_jup_0, v_jup_0

(array([-3.13499559e+11,  7.16531655e+11,  4.04379637e+09]),
 array([-12125.37715192,  -4618.63890634,    290.51092555]))

In [15]:
deltat = 1 * 86400 # 1 día en segundos
r_jup_dt = r_jup_0 + v_jup_0 * deltat
r_sol_dt = r_sol_0 + v_sol_0 * deltat

r_jup_dt, r_sol_dt

(array([-3.14547192e+11,  7.16132604e+11,  4.06889651e+09]),
 array([-3.98212869e+08, -8.23983372e+08,  1.85220337e+07]))

In [18]:
mu_sol = pc.constantes.mu_sun
mu_jup = pc.constantes.mu_jupiter
rij_vec = r_jup_0 - r_sol_0
v_jup_dt = v_jup_0 - mu_sol * rij_vec / np.linalg.norm(rij_vec)**3 * deltat

v_jup_dt

array([-12117.89040582,  -4635.79206931,    290.41467508])

In [19]:
# aceleración sobre el Sol debida a Júpiter (vector de r del Sol hacia Júpiter = -rij_vec)
# el signo queda positivo porque rij_vec = r_jup_0 - r_sol_0
v_sol_dt = v_sol_0 + mu_jup * rij_vec / np.linalg.norm(rij_vec)**3 * deltat
v_sol_dt

array([12.2036746 ,  1.25570472, -0.24251222])